const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Behaviors.LOS,
		C3.Behaviors.Physics,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Behaviors.scrollto,
		C3.Behaviors.MoveTo,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Behaviors.solid,
		C3.Behaviors.Rotate,
		C3.Behaviors.Anchor,
		C3.Behaviors.Fade,
		C3.Plugins.Touch,
		C3.Plugins.Button,
		C3.Plugins.Particles,
		C3.Plugins.LocalStorage,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Behaviors.Flash,
		C3.Plugins.GD_SDK,
		C3.Behaviors.destroy,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Behaviors.Physics.Acts.ApplyTorque,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Particles.Acts.SetTimeout,
		C3.Plugins.Particles.Acts.SetInitSize,
		C3.Plugins.Particles.Acts.MoveToBottom,
		C3.Plugins.Particles.Acts.SetGravity,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Particles.Cnds.IsVisible,
		C3.Plugins.Particles.Acts.SetZElevation,
		C3.Plugins.Particles.Exps.ZElevation,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Physics.Acts.ApplyImpulseToward,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Pin.Cnds.IsPinned,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Behaviors.Physics.Acts.ApplyTorqueToAngle,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Cnds.IsEffectEnabled,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Behaviors.Physics.Acts.RemoveJoints,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.Physics.Cnds.IsEnabled,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetElasticity,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Pin.Cnds.WillDestroy,
		C3.Plugins.Particles.Acts.SetSprayCone,
		C3.Plugins.Particles.Acts.SetXRandomiser,
		C3.Plugins.Particles.Acts.SetYRandomiser,
		C3.Plugins.Particles.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.GD_SDK.Acts.ShowAd,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Behaviors.Physics.Acts.CreateLimitedRevoluteJoint,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.RotateTowardAngle,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Behaviors.Bullet.Exps.Gravity,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Behaviors.Physics.Acts.SetDensity,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.JavaScriptInEvents.Estorage_Event1_Act1,
		C3.Plugins.Text.Acts.SetFontFace,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.GD_SDK.Acts.ShowRewardedAd,
		C3.Plugins.GD_SDK.Cnds.RewardPlayer,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.GD_SDK.Cnds.PauseGame,
		C3.Plugins.GD_SDK.Cnds.ResumeGame,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.GD_SDK.Acts.PreloadRewardedAd,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Behaviors.Anchor.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Physics.Acts.ApplyImpulse,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Mouse.Acts.SetCursor
	];
};
self.C3_JsPropNameTable = [
	{electiric: 0},
	{or_govde: 0},
	{or_baldir_sol: 0},
	{or_bas: 0},
	{Pin: 0},
	{or_yay: 0},
	{or_ip_ust: 0},
	{tree_ok: 0},
	{ok_number: 0},
	{or_ok: 0},
	{blue_govde: 0},
	{blue_bas: 0},
	{blue_bacak_sag: 0},
	{blue_yay: 0},
	{blue_ok: 0},
	{blue_ip_ust: 0},
	{or_baldir_sag: 0},
	{or_bacak_sag: 0},
	{or_bacak_sol: 0},
	{or_kol_sag: 0},
	{or_kol_sol: 0},
	{or_bilek_sol: 0},
	{or_bilek_sag: 0},
	{blue_bacak_sol: 0},
	{blue_baldir_sol: 0},
	{blue_baldir_sag: 0},
	{blue_kol_sol: 0},
	{blue_kol_sag: 0},
	{blue_bilek_sag: 0},
	{blue_bilek_sol: 0},
	{Mouse: 0},
	{or_ip_alt: 0},
	{saplandi: 0},
	{Bullet: 0},
	{LineOfSight: 0},
	{Physics: 0},
	{Sine: 0},
	{or_ok2: 0},
	{or_speed: 0},
	{Keyboard: 0},
	{blue_ip_alt: 0},
	{ozel_ok: 0},
	{blue_ok2: 0},
	{blue_speed: 0},
	{Audio: 0},
	{z_Camera_Object_A: 0},
	{z_Camera_Object_Line: 0},
	{z_Camera_Object_Camera2: 0},
	{playercamactive: 0},
	{ScrollTo: 0},
	{MoveTo2: 0},
	{z_Camera_Object_Camera: 0},
	{z_Camera_Object_B: 0},
	{DragDrop: 0},
	{Tween: 0},
	{camera: 0},
	{tugla_kiran: 0},
	{apple: 0},
	{scores: 0},
	{winss: 0},
	{Solid: 0},
	{or_helmet: 0},
	{blue_ok_part_1: 0},
	{blue_ok_part_2: 0},
	{blue_ok_part_3: 0},
	{or_ok_part_1: 0},
	{or_ok_part_2: 0},
	{or_ok_part_3: 0},
	{blue_helmet: 0},
	{or_col: 0},
	{destroyer: 0},
	{or_helmet_icon: 0},
	{Rotate: 0},
	{bonus_spawner: 0},
	{or_speed2: 0},
	{my_shield: 0},
	{blue_shield: 0},
	{bonus_bomb: 0},
	{Anchor: 0},
	{helmet_button_pwr: 0},
	{play_button_pwr: 0},
	{adventure_taban_bg: 0},
	{Fade: 0},
	{gold_reward: 0},
	{BGBUTON: 0},
	{money_number_text: 0},
	{"3_arrows_price_text_pwr": 0},
	{blue_score3_pwr: 0},
	{helmet_price_text_pwr: 0},
	{day_text: 0},
	{ADVENTURE_MODE_TEXT: 0},
	{head_shot_text: 0},
	{tree_arrows_button_pwr: 0},
	{Shield_button_pwr: 0},
	{Touch: 0},
	{play_text: 0},
	{shield_price_text_pwr: 0},
	{blue_healt_frame: 0},
	{blue_health2_clone1: 0},
	{blue_bacak_sag_clone1: 0},
	{blue_govde_clone1: 0},
	{blue_bas_clone1: 0},
	{blue_baldir_sol_clone1: 0},
	{blue_baldir_sag_clone1: 0},
	{blue_bacak_sol_clone1: 0},
	{blue_bilek_sag_clone1: 0},
	{blue_bilek_sol_clone1: 0},
	{blue_kol_sol_clone1: 0},
	{blue_kol_sag_clone1: 0},
	{blue_yay_clone1: 0},
	{blue_ip_alt_clone1: 0},
	{blue_ip_ust_clone1: 0},
	{blue_ok_clone1: 0},
	{blue_health2: 0},
	{blue_healt_frame_clone1: 0},
	{blue_bacak_sag_clone2: 0},
	{blue_yay_clone2: 0},
	{blue_kol_sol_clone2: 0},
	{blue_kol_sag_clone2: 0},
	{blue_govde_clone2: 0},
	{blue_bilek_sol_clone2: 0},
	{blue_bilek_sag_clone2: 0},
	{blue_bas_clone2: 0},
	{blue_baldir_sol_clone2: 0},
	{blue_baldir_sag_clone2: 0},
	{blue_bacak_sol_clone2: 0},
	{blue_ip_alt_clone2: 0},
	{blue_ip_ust_clone2: 0},
	{blue_ok_clone2: 0},
	{blue_health2_clone2: 0},
	{blue_healt_frame_clone2: 0},
	{blue_bacak_sag_clone3: 0},
	{blue_yay_clone3: 0},
	{blue_kol_sol_clone3: 0},
	{blue_kol_sag_clone3: 0},
	{blue_govde_clone3: 0},
	{blue_bilek_sol_clone3: 0},
	{blue_bilek_sag_clone3: 0},
	{blue_bas_clone3: 0},
	{blue_baldir_sol_clone3: 0},
	{blue_baldir_sag_clone3: 0},
	{blue_bacak_sol_clone3: 0},
	{blue_ip_alt_clone3: 0},
	{blue_ip_ust_clone3: 0},
	{blue_ok_clone3: 0},
	{blue_health2_clone3: 0},
	{blue_healt_frame_clone3: 0},
	{blue_bacak_sag_clone4: 0},
	{blue_yay_clone4: 0},
	{blue_kol_sol_clone4: 0},
	{blue_kol_sag_clone4: 0},
	{blue_govde_clone4: 0},
	{blue_bilek_sol_clone4: 0},
	{blue_bilek_sag_clone4: 0},
	{blue_bas_clone4: 0},
	{blue_baldir_sol_clone4: 0},
	{blue_baldir_sag_clone4: 0},
	{blue_bacak_sol_clone4: 0},
	{blue_ip_alt_clone4: 0},
	{blue_ip_ust_clone4: 0},
	{blue_ok_clone4: 0},
	{blue_health2_clone4: 0},
	{blue_healt_frame_clone4: 0},
	{sag: 0},
	{sol: 0},
	{helmet_buyed_text_pwr: 0},
	{"3arrows_buyed_text_pwr": 0},
	{Shield_buyed_text_pwr: 0},
	{health_zone: 0},
	{health_particle: 0},
	{health_particle2: 0},
	{health_particle3: 0},
	{scale_text: 0},
	{sagsol: 0},
	{hommm_button: 0},
	{adventuremod_button: 0},
	{RewardedAdButton: 0},
	{MidgameAdButton: 0},
	{ParticlesAmbience: 0},
	{varolus: 0},
	{sagit: 0},
	{solit: 0},
	{aktif: 0},
	{up_arrow_button: 0},
	{arrow_name2: 0},
	{ARROW_BUY_BUTTON2: 0},
	{shield_price_text2: 0},
	{Shield_buyed_text2: 0},
	{blue_score4: 0},
	{shield_price_text3: 0},
	{x_text: 0},
	{ozel_ok_sayisi: 0},
	{kim: 0},
	{electiric_kivilcim_or: 0},
	{skull_bacak: 0},
	{skull_govde: 0},
	{skull_bas: 0},
	{skull_kol: 0},
	{enemy_pixel_part: 0},
	{ok_missile_klavuz: 0},
	{DEFAULT_BUTTON_chs: 0},
	{CHOOSE_FRAME: 0},
	{BUYX3: 0},
	{FIRE_BUTTON_chs: 0},
	{ELECTIRIC_BUTTON_chs: 0},
	{PIXELLAR_BUTTON_chs: 0},
	{MISSILE_BUTTON_chs: 0},
	{POISON_BUTTON_chs: 0},
	{choose_arrow_bg2p: 0},
	{ROCKET_BUTTON_chs: 0},
	{CHOOSE_FRAME2: 0},
	{bomba: 0},
	{ok_missile_klavuz_blues: 0},
	{bomba_blues: 0},
	{"321go": 0},
	{endscrleftbtn_tank_mayhem: 0},
	{endscrrightbtn_tank_mayhem: 0},
	{endscre: 0},
	{or_scoree: 0},
	{blue_scoree: 0},
	{zemplay: 0},
	{black_ok: 0},
	{or_kaide: 0},
	{LocalStorage: 0},
	{healthbuybutton_ugrade: 0},
	{text_ugrade: 0},
	{POWER_BAR_ugrade: 0},
	{ARMOR_BAR_ugrade: 0},
	{HEALTH_BAR_ugrade: 0},
	{BALANCE_BAR_ugrade: 0},
	{powerupgrade_price_text_ugrade: 0},
	{shieldupgrade_text_ugrade: 0},
	{healthupgrade_text_ugrade: 0},
	{balanceupgrade_price_ugradet: 0},
	{"3arrow_BAR_ugrade": 0},
	{helmet_BAR_ugrade: 0},
	{win_reward_panel: 0},
	{button_rocket_buy3: 0},
	{highscore_mod_button: 0},
	{HIGHSCORE_MOD_TEXT: 0},
	{twp_mode_button: 0},
	{TWOPLAYERMODE_TEXT: 0},
	{FADE: 0},
	{shieldbuybutton_ugrade: 0},
	{powerbuybutton_ugrade: 0},
	{arrow_damage_button_ugrade: 0},
	{"3_arrowbuybutton_ugrade": 0},
	{helmetbuybutton_ugrade: 0},
	{"3arrowupgrade_price_ugrade": 0},
	{helmetupgrade_price_ugrade: 0},
	{balance_upgrade_price_text3: 0},
	{reward: 0},
	{reward_fisek: 0},
	{fisek_patlayan_iz: 0},
	{patlama: 0},
	{sandik_part: 0},
	{Reward_text: 0},
	{start_page_bg: 0},
	{logo_alt_zemin: 0},
	{Text2: 0},
	{click_kenar: 0},
	{click_to_continue: 0},
	{panels_ugrade: 0},
	{gold_reward2: 0},
	{gold_reward3: 0},
	{BGBUTON2: 0},
	{choose_arrow_tasiyici: 0},
	{helmeticon_ugrade: 0},
	{armoricon_ugrade: 0},
	{povericon_ugrade: 0},
	{balanceicon_ugrade: 0},
	{healthicon_ugrade: 0},
	{lucky_reward: 0},
	{luck_frame: 0},
	{spin_again_button: 0},
	{go_to_menu_button: 0},
	{next_battle_button: 0},
	{wins_panel_black_bg: 0},
	{"3arrowicon_ugrade": 0},
	{rise_effect: 0},
	{skull: 0},
	{drygdf: 0},
	{dead_text: 0},
	{BGBUTON3: 0},
	{BGBUTON4: 0},
	{OK_SEC_TABAN: 0},
	{shield_money: 0},
	{"3arrow_money": 0},
	{helmet_money: 0},
	{headshot_reward: 0},
	{DEAD_BG: 0},
	{replay_button: 0},
	{replay_reward_button: 0},
	{win_fisek: 0},
	{dead_reward: 0},
	{day_reward: 0},
	{reward_info_text: 0},
	{reward_al_button: 0},
	{unlem: 0},
	{upgrade_info_text: 0},
	{ON2_pwr: 0},
	{gold_reward_menu: 0},
	{or_bilek_baglanti: 0},
	{or_ok_baglanti: 0},
	{"2pbonus": 0},
	{RAPID3: 0},
	{skull2: 0},
	{BGBUTON6: 0},
	{hommm3: 0},
	{apple_tasiyici: 0},
	{kimvurdu: 0},
	{obje_gaz: 0},
	{ucan_kaya_blue: 0},
	{obje_sandik: 0},
	{addcoin: 0},
	{ON3: 0},
	{reset: 0},
	{or_el_sol: 0},
	{or_el_sag: 0},
	{Blue_el_sag_clone_3: 0},
	{Blue_el_sol_clone_3: 0},
	{PlatformInfo: 0},
	{joybg: 0},
	{joy: 0},
	{line: 0},
	{lineangle: 0},
	{linewidht: 0},
	{iplik: 0},
	{iplik2: 0},
	{speedd: 0},
	{FireworkParticles: 0},
	{kansplash_Particles: 0},
	{kan_Particles: 0},
	{ok_hit: 0},
	{ok_hit_tas_spawner: 0},
	{ok_hit2: 0},
	{poison_particles_or: 0},
	{fire_particles_or: 0},
	{duman_particles_or: 0},
	{pixel_particles_or: 0},
	{HOME: 0},
	{touch_hit: 0},
	{touch_line_effect: 0},
	{touch_line_effect2: 0},
	{fire_impact_particles_or: 0},
	{col: 0},
	{missile_iz_or: 0},
	{missile_particles_or: 0},
	{govde_duman_particles: 0},
	{electiric_light_or: 0},
	{bomba_fire_particles: 0},
	{bomba_duman_particles: 0},
	{headshot_reward2: 0},
	{"2p_blue_touch": 0},
	{"2p_orange_touch": 0},
	{on_off: 0},
	{upgradepanel_tasiyici_button: 0},
	{Browser: 0},
	{ok_yol: 0},
	{Sprite: 0},
	{joy2: 0},
	{upgradepanel_bg: 0},
	{upgrade_panel_line: 0},
	{fire_particles_blue: 0},
	{missile_particles_blue: 0},
	{missile_iz_or_blue: 0},
	{poison_particles_blue: 0},
	{pixel_particles_blue: 0},
	{duman_particles_blue: 0},
	{electiric_light_blue: 0},
	{electiric_kivilcim_blue: 0},
	{fire_impact_particles_blue: 0},
	{bomb_sarapnel: 0},
	{touch_tutorial: 0},
	{TouchandPull: 0},
	{lock1: 0},
	{lock2: 0},
	{lock3: 0},
	{step: 0},
	{touch_tutorial_unlock: 0},
	{bomb_collison: 0},
	{or_scoree2: 0},
	{Sprite2: 0},
	{HEALTH_BAR_ugrade2: 0},
	{Arm_power: 0},
	{arm_power_bonus: 0},
	{health_power_bonus: 0},
	{arm_zone: 0},
	{arm_particle: 0},
	{ok_hit3: 0},
	{health_power_crash: 0},
	{arm_power_crash: 0},
	{endscre2: 0},
	{touch_area: 0},
	{hand_light: 0},
	{bomb_knife: 0},
	{gunfruit1_knife: 0},
	{bomb_fitil: 0},
	{gunfruit1_knife2: 0},
	{MoveTo: 0},
	{"3xcombo": 0},
	{fruit_bomb: 0},
	{"2xcombo": 0},
	{or_ok2_knife_hit: 0},
	{knifee: 0},
	{Text: 0},
	{Text3: 0},
	{upgrade_info_text2: 0},
	{text_ugrade2: 0},
	{text_ugrade3: 0},
	{text_ugrade4: 0},
	{text_ugrade5: 0},
	{text_ugrade6: 0},
	{text_ugrade7: 0},
	{ON2_pwr2: 0},
	{ON2_pwr3: 0},
	{Flash: 0},
	{choose_arrow_t: 0},
	{health_text_ui: 0},
	{arm_power_text_ui: 0},
	{Text4: 0},
	{Sound_On_Off_Button: 0},
	{Text5: 0},
	{Text6: 0},
	{home_mods: 0},
	{sandik_particle: 0},
	{Text7: 0},
	{unlock_arrow: 0},
	{unlock_arrow_text: 0},
	{blue_body_part: 0},
	{game_tutorial: 0},
	{arrowUnlocked: 0},
	{upgrade_zemin_ugrade: 0},
	{thunder_BUTTON_chs: 0},
	{saw_BUTTON_chs: 0},
	{fuze_BUTTON_chs: 0},
	{freeze_BUTTON_chs: 0},
	{meteor_BUTTON_chs: 0},
	{ayak_sol: 0},
	{ayak_sag: 0},
	{Sprite3: 0},
	{testere: 0},
	{Ice_CPU: 0},
	{addcoin2: 0},
	{ice: 0},
	{freeeze_particle: 0},
	{freeze_expl_particle: 0},
	{yildirim: 0},
	{meteor: 0},
	{meteor_particle: 0},
	{simsek: 0},
	{yildirim_patlama: 0},
	{meteor_uc: 0},
	{meteordalga: 0},
	{meteordalga2: 0},
	{ok_fuze: 0},
	{fuze: 0},
	{fuze_particle: 0},
	{panels_ugrade2: 0},
	{panels_ugrade3: 0},
	{power_tutorial: 0},
	{ParticlesAmbience2: 0},
	{random_arrow_button: 0},
	{panels_ugrade4: 0},
	{HEALTH_BAR_ugrade3: 0},
	{RAPID4: 0},
	{"2p_play_button": 0},
	{EndScore: 0},
	{ParticlesAmbience3: 0},
	{kukla1: 0},
	{kukla2: 0},
	{kukla3: 0},
	{kuklatoz: 0},
	{blue_ayak_sol_clone3: 0},
	{blue_ayak_sag_clone3: 0},
	{kaya1: 0},
	{kaya2: 0},
	{kaya3: 0},
	{kaya4: 0},
	{kaya5: 0},
	{kaya6: 0},
	{kaya_particle: 0},
	{kaya_duman_particle: 0},
	{Sprite4: 0},
	{el: 0},
	{el1: 0},
	{el2: 0},
	{el3: 0},
	{el4: 0},
	{okiz: 0},
	{okiz2: 0},
	{shield_sn_text: 0},
	{"3arrow_sn_text": 0},
	{helmet_sn_text: 0},
	{pixel_particles_boom: 0},
	{arm_power_miktar: 0},
	{health_miktar: 0},
	{arrow_damage_miktar: 0},
	{boss_konusma: 0},
	{ucan_kaya_or: 0},
	{obje_kaya: 0},
	{fire_impact_particles_black: 0},
	{yildirim_expl_particle: 0},
	{GameDistributionSDK: 0},
	{Text8: 0},
	{Text9: 0},
	{Sprite5: 0},
	{Text10: 0},
	{Sprite6: 0},
	{panels_ugrade5: 0},
	{gold_reward4: 0},
	{Text9_replay: 0},
	{or_fizik: 0},
	{blue_fizik: 0},
	{blue_archer: 0},
	{or_archer: 0},
	{hersey: 0},
	{or_body: 0},
	{blue_body: 0},
	{dest: 0},
	{button: 0},
	{blue_archer_clone1: 0},
	{blue_body_clone1: 0},
	{blue_fizik_clone1: 0},
	{blue_fizik_clone2: 0},
	{blue_archer_clone2: 0},
	{blue_body_clone2: 0},
	{blue_fizik_clone3: 0},
	{blue_body_clone3: 0},
	{blue_archer_clone3: 0},
	{blue_fizik_clone4: 0},
	{blue_body_clone4: 0},
	{blue_archer_clone4: 0},
	{yay: 0},
	{helmets: 0},
	{choose_arrow: 0},
	{blues_all: 0},
	{wait_dest: 0},
	{kemik: 0},
	{shields: 0},
	{tas_spawner: 0},
	{choose_arrow_image: 0},
	{choose_arrow_text: 0},
	{finish_tween: 0},
	{parts: 0},
	{upgrade_panel: 0},
	{Text_ugradepanel: 0},
	{blue_archer_all: 0},
	{fruit_dest: 0},
	{menu_game_dest_text: 0},
	{menu_game_destroy: 0},
	{all_texts: 0},
	{game_butn: 0},
	{DestroyOutsideLayout2: 0},
	{sahnedisiyokol: 0},
	{blue_archer_all1: 0},
	{blue_archer_all2: 0},
	{blue_archer_all3: 0},
	{blue_archer_all4: 0},
	{kuklafizik: 0},
	{blues_target: 0},
	{or_archer_target: 0},
	{kayafam: 0},
	{or_archer_all: 0},
	{objeler: 0},
	{or_bullet_speed: 0},
	{blue_bullet_speed: 0},
	{blue_lost: 0},
	{or_lost: 0},
	{or_health: 0},
	{blue_health: 0},
	{or_score: 0},
	{blue_score: 0},
	{kamerastop: 0},
	{layoutscalell: 0},
	{Camera: 0},
	{blue_bullet_speed_clone1: 0},
	{blue_lost_clone1: 0},
	{blue_health_clone1: 0},
	{orange_bonus: 0},
	{blue_bullet_speed_clone2: 0},
	{blue_lost_clone2: 0},
	{blue_health_clone2: 0},
	{blue_bullet_speed_clone3: 0},
	{blue_lost_clone3: 0},
	{blue_health_clone3: 0},
	{blue_score_clone3: 0},
	{blue_bullet_speed_clone4: 0},
	{blue_lost_clone4: 0},
	{blue_health_clone4: 0},
	{day: 0},
	{dead_number: 0},
	{money: 0},
	{Headshoot_number: 0},
	{blue_ai: 0},
	{blue_ai_clone1: 0},
	{blue_ai_clone2: 0},
	{blue_ai_clone3: 0},
	{blue_ai_clone4: 0},
	{ai_arrow_power: 0},
	{sag_sol_fark: 0},
	{adventure_or_2p_or_1pcpu: 0},
	{secili_ok_ai3: 0},
	{"321_go": 0},
	{NEXT_OR_AGAIN: 0},
	{or_alinan_hasar: 0},
	{or_verilen_hasar: 0},
	{tree_ok_sn: 0},
	{shield_sn: 0},
	{helmet_sn: 0},
	{spin: 0},
	{stop_next: 0},
	{arm_power: 0},
	{armpower: 0},
	{ai_target: 0},
	{up_down: 0},
	{left_right: 0},
	{shield_geri_sayim: 0},
	{helmet_geri_sayim: 0},
	{treeok_geri_sayim: 0},
	{oyun_modu: 0},
	{mesafe: 0},
	{seviyede_kazanilan_para: 0},
	{line_angle: 0},
	{line_widht: 0},
	{distanceAllowed: 0},
	{end_scr: 0},
	{or_helmet_kazandi: 0},
	{or_shield_kazandi: 0},
	{or_3ok_kazandi: 0},
	{Progress: 0},
	{reward_secim: 0},
	{graphic_quality2: 0},
	{sound2: 0},
	{htp2: 0},
	{head_shoot_gold: 0},
	{dead_gold: 0},
	{day_gold: 0},
	{tutorial_step: 0},
	{or_tree_ok: 0},
	{or_shield: 0},
	{secili_ok: 0},
	{hasarbar: 0},
	{bulletbar: 0},
	{health_upgrade_price: 0},
	{arrow_damage_upgrade_price: 0},
	{"3arrow_upgrade_price": 0},
	{power_upgrade_price: 0},
	{helmet_upgrade_price: 0},
	{shield_upgrade_price: 0},
	{Main_Sound: 0},
	{ses: 0},
	{ilk_kan: 0}
];

self.InstanceType = {
	or_govde: class extends self.ISpriteInstance {},
	or_baldir_sol: class extends self.ISpriteInstance {},
	or_bas: class extends self.ISpriteInstance {},
	or_yay: class extends self.ISpriteInstance {},
	or_ip_ust: class extends self.ISpriteInstance {},
	or_ok: class extends self.ISpriteInstance {},
	blue_govde: class extends self.ISpriteInstance {},
	blue_bas: class extends self.ISpriteInstance {},
	blue_bacak_sag: class extends self.ISpriteInstance {},
	blue_yay: class extends self.ISpriteInstance {},
	blue_ok: class extends self.ISpriteInstance {},
	blue_ip_ust: class extends self.ISpriteInstance {},
	or_baldir_sag: class extends self.ISpriteInstance {},
	or_bacak_sag: class extends self.ISpriteInstance {},
	or_bacak_sol: class extends self.ISpriteInstance {},
	or_kol_sag: class extends self.ISpriteInstance {},
	or_kol_sol: class extends self.ISpriteInstance {},
	or_bilek_sol: class extends self.ISpriteInstance {},
	or_bilek_sag: class extends self.ISpriteInstance {},
	blue_bacak_sol: class extends self.ISpriteInstance {},
	blue_baldir_sol: class extends self.ISpriteInstance {},
	blue_baldir_sag: class extends self.ISpriteInstance {},
	blue_kol_sol: class extends self.ISpriteInstance {},
	blue_kol_sag: class extends self.ISpriteInstance {},
	blue_bilek_sag: class extends self.ISpriteInstance {},
	blue_bilek_sol: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	or_ip_alt: class extends self.ISpriteInstance {},
	or_ok2: class extends self.ISpriteInstance {},
	or_speed: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	blue_ip_alt: class extends self.ISpriteInstance {},
	blue_ok2: class extends self.ISpriteInstance {},
	blue_speed: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	z_Camera_Object_A: class extends self.ISpriteInstance {},
	z_Camera_Object_Line: class extends self.ISpriteInstance {},
	z_Camera_Object_Camera2: class extends self.ISpriteInstance {},
	z_Camera_Object_Camera: class extends self.ISpriteInstance {},
	z_Camera_Object_B: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	tugla_kiran: class extends self.ISpriteInstance {},
	apple: class extends self.ISpriteInstance {},
	scores: class extends self.ISpriteInstance {},
	winss: class extends self.ISpriteInstance {},
	or_helmet: class extends self.ISpriteInstance {},
	blue_ok_part_1: class extends self.ISpriteInstance {},
	blue_ok_part_2: class extends self.ISpriteInstance {},
	blue_ok_part_3: class extends self.ISpriteInstance {},
	or_ok_part_1: class extends self.ISpriteInstance {},
	or_ok_part_2: class extends self.ISpriteInstance {},
	or_ok_part_3: class extends self.ISpriteInstance {},
	blue_helmet: class extends self.ISpriteInstance {},
	or_col: class extends self.ISpriteInstance {},
	destroyer: class extends self.ISpriteInstance {},
	or_helmet_icon: class extends self.ISpriteInstance {},
	bonus_spawner: class extends self.ISpriteInstance {},
	or_speed2: class extends self.ITextInstance {},
	my_shield: class extends self.ISpriteInstance {},
	blue_shield: class extends self.ISpriteInstance {},
	bonus_bomb: class extends self.ISpriteInstance {},
	helmet_button_pwr: class extends self.ISpriteInstance {},
	play_button_pwr: class extends self.ISpriteInstance {},
	adventure_taban_bg: class extends self.ISpriteInstance {},
	gold_reward: class extends self.ISpriteInstance {},
	BGBUTON: class extends self.ISpriteInstance {},
	money_number_text: class extends self.ITextInstance {},
	_3_arrows_price_text_pwr: class extends self.ITextInstance {},
	blue_score3_pwr: class extends self.ISpriteInstance {},
	helmet_price_text_pwr: class extends self.ITextInstance {},
	day_text: class extends self.ITextInstance {},
	ADVENTURE_MODE_TEXT: class extends self.ITextInstance {},
	head_shot_text: class extends self.ITextInstance {},
	tree_arrows_button_pwr: class extends self.ISpriteInstance {},
	Shield_button_pwr: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	play_text: class extends self.ITextInstance {},
	shield_price_text_pwr: class extends self.ITextInstance {},
	blue_healt_frame: class extends self.ISpriteInstance {},
	blue_health2_clone1: class extends self.ISpriteInstance {},
	blue_bacak_sag_clone1: class extends self.ISpriteInstance {},
	blue_govde_clone1: class extends self.ISpriteInstance {},
	blue_bas_clone1: class extends self.ISpriteInstance {},
	blue_baldir_sol_clone1: class extends self.ISpriteInstance {},
	blue_baldir_sag_clone1: class extends self.ISpriteInstance {},
	blue_bacak_sol_clone1: class extends self.ISpriteInstance {},
	blue_bilek_sag_clone1: class extends self.ISpriteInstance {},
	blue_bilek_sol_clone1: class extends self.ISpriteInstance {},
	blue_kol_sol_clone1: class extends self.ISpriteInstance {},
	blue_kol_sag_clone1: class extends self.ISpriteInstance {},
	blue_yay_clone1: class extends self.ISpriteInstance {},
	blue_ip_alt_clone1: class extends self.ISpriteInstance {},
	blue_ip_ust_clone1: class extends self.ISpriteInstance {},
	blue_ok_clone1: class extends self.ISpriteInstance {},
	blue_health2: class extends self.ISpriteInstance {},
	blue_healt_frame_clone1: class extends self.ISpriteInstance {},
	blue_bacak_sag_clone2: class extends self.ISpriteInstance {},
	blue_yay_clone2: class extends self.ISpriteInstance {},
	blue_kol_sol_clone2: class extends self.ISpriteInstance {},
	blue_kol_sag_clone2: class extends self.ISpriteInstance {},
	blue_govde_clone2: class extends self.ISpriteInstance {},
	blue_bilek_sol_clone2: class extends self.ISpriteInstance {},
	blue_bilek_sag_clone2: class extends self.ISpriteInstance {},
	blue_bas_clone2: class extends self.ISpriteInstance {},
	blue_baldir_sol_clone2: class extends self.ISpriteInstance {},
	blue_baldir_sag_clone2: class extends self.ISpriteInstance {},
	blue_bacak_sol_clone2: class extends self.ISpriteInstance {},
	blue_ip_alt_clone2: class extends self.ISpriteInstance {},
	blue_ip_ust_clone2: class extends self.ISpriteInstance {},
	blue_ok_clone2: class extends self.ISpriteInstance {},
	blue_health2_clone2: class extends self.ISpriteInstance {},
	blue_healt_frame_clone2: class extends self.ISpriteInstance {},
	blue_bacak_sag_clone3: class extends self.ISpriteInstance {},
	blue_yay_clone3: class extends self.ISpriteInstance {},
	blue_kol_sol_clone3: class extends self.ISpriteInstance {},
	blue_kol_sag_clone3: class extends self.ISpriteInstance {},
	blue_govde_clone3: class extends self.ISpriteInstance {},
	blue_bilek_sol_clone3: class extends self.ISpriteInstance {},
	blue_bilek_sag_clone3: class extends self.ISpriteInstance {},
	blue_bas_clone3: class extends self.ISpriteInstance {},
	blue_baldir_sol_clone3: class extends self.ISpriteInstance {},
	blue_baldir_sag_clone3: class extends self.ISpriteInstance {},
	blue_bacak_sol_clone3: class extends self.ISpriteInstance {},
	blue_ip_alt_clone3: class extends self.ISpriteInstance {},
	blue_ip_ust_clone3: class extends self.ISpriteInstance {},
	blue_ok_clone3: class extends self.ISpriteInstance {},
	blue_health2_clone3: class extends self.ISpriteInstance {},
	blue_healt_frame_clone3: class extends self.ISpriteInstance {},
	blue_bacak_sag_clone4: class extends self.ISpriteInstance {},
	blue_yay_clone4: class extends self.ISpriteInstance {},
	blue_kol_sol_clone4: class extends self.ISpriteInstance {},
	blue_kol_sag_clone4: class extends self.ISpriteInstance {},
	blue_govde_clone4: class extends self.ISpriteInstance {},
	blue_bilek_sol_clone4: class extends self.ISpriteInstance {},
	blue_bilek_sag_clone4: class extends self.ISpriteInstance {},
	blue_bas_clone4: class extends self.ISpriteInstance {},
	blue_baldir_sol_clone4: class extends self.ISpriteInstance {},
	blue_baldir_sag_clone4: class extends self.ISpriteInstance {},
	blue_bacak_sol_clone4: class extends self.ISpriteInstance {},
	blue_ip_alt_clone4: class extends self.ISpriteInstance {},
	blue_ip_ust_clone4: class extends self.ISpriteInstance {},
	blue_ok_clone4: class extends self.ISpriteInstance {},
	blue_health2_clone4: class extends self.ISpriteInstance {},
	blue_healt_frame_clone4: class extends self.ISpriteInstance {},
	sag: class extends self.ISpriteInstance {},
	sol: class extends self.ISpriteInstance {},
	helmet_buyed_text_pwr: class extends self.ITextInstance {},
	_3arrows_buyed_text_pwr: class extends self.ITextInstance {},
	Shield_buyed_text_pwr: class extends self.ITextInstance {},
	health_zone: class extends self.ISpriteInstance {},
	health_particle: class extends self.ISpriteInstance {},
	health_particle2: class extends self.ISpriteInstance {},
	health_particle3: class extends self.ISpriteInstance {},
	scale_text: class extends self.ITextInstance {},
	sagsol: class extends self.ITextInstance {},
	hommm_button: class extends self.ISpriteInstance {},
	adventuremod_button: class extends self.ISpriteInstance {},
	RewardedAdButton: class extends self.IButtonInstance {},
	MidgameAdButton: class extends self.IButtonInstance {},
	ParticlesAmbience: class extends self.IParticlesInstance {},
	varolus: class extends self.ISpriteInstance {},
	sagit: class extends self.ISpriteInstance {},
	solit: class extends self.ISpriteInstance {},
	aktif: class extends self.ISpriteInstance {},
	up_arrow_button: class extends self.ISpriteInstance {},
	arrow_name2: class extends self.ITextInstance {},
	ARROW_BUY_BUTTON2: class extends self.ISpriteInstance {},
	shield_price_text2: class extends self.ITextInstance {},
	Shield_buyed_text2: class extends self.ITextInstance {},
	blue_score4: class extends self.ISpriteInstance {},
	shield_price_text3: class extends self.ITextInstance {},
	x_text: class extends self.ITextInstance {},
	ozel_ok_sayisi: class extends self.ITextInstance {},
	electiric_kivilcim_or: class extends self.ISpriteInstance {},
	skull_bacak: class extends self.ISpriteInstance {},
	skull_govde: class extends self.ISpriteInstance {},
	skull_bas: class extends self.ISpriteInstance {},
	skull_kol: class extends self.ISpriteInstance {},
	enemy_pixel_part: class extends self.ISpriteInstance {},
	ok_missile_klavuz: class extends self.ISpriteInstance {},
	DEFAULT_BUTTON_chs: class extends self.ISpriteInstance {},
	CHOOSE_FRAME: class extends self.ISpriteInstance {},
	BUYX3: class extends self.ITextInstance {},
	FIRE_BUTTON_chs: class extends self.ISpriteInstance {},
	ELECTIRIC_BUTTON_chs: class extends self.ISpriteInstance {},
	PIXELLAR_BUTTON_chs: class extends self.ISpriteInstance {},
	MISSILE_BUTTON_chs: class extends self.ISpriteInstance {},
	POISON_BUTTON_chs: class extends self.ISpriteInstance {},
	choose_arrow_bg2p: class extends self.ISpriteInstance {},
	ROCKET_BUTTON_chs: class extends self.ISpriteInstance {},
	CHOOSE_FRAME2: class extends self.ISpriteInstance {},
	bomba: class extends self.ISpriteInstance {},
	ok_missile_klavuz_blues: class extends self.ISpriteInstance {},
	bomba_blues: class extends self.ISpriteInstance {},
	_321go: class extends self.ITextInstance {},
	endscrleftbtn_tank_mayhem: class extends self.ISpriteInstance {},
	endscrrightbtn_tank_mayhem: class extends self.ISpriteInstance {},
	endscre: class extends self.ITextInstance {},
	or_scoree: class extends self.ITextInstance {},
	blue_scoree: class extends self.ITextInstance {},
	zemplay: class extends self.ISpriteInstance {},
	black_ok: class extends self.ISpriteInstance {},
	or_kaide: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	healthbuybutton_ugrade: class extends self.ISpriteInstance {},
	text_ugrade: class extends self.ITextInstance {},
	POWER_BAR_ugrade: class extends self.ISpriteInstance {},
	ARMOR_BAR_ugrade: class extends self.ISpriteInstance {},
	HEALTH_BAR_ugrade: class extends self.ISpriteInstance {},
	BALANCE_BAR_ugrade: class extends self.ISpriteInstance {},
	powerupgrade_price_text_ugrade: class extends self.ITextInstance {},
	shieldupgrade_text_ugrade: class extends self.ITextInstance {},
	healthupgrade_text_ugrade: class extends self.ITextInstance {},
	balanceupgrade_price_ugradet: class extends self.ITextInstance {},
	_3arrow_BAR_ugrade: class extends self.ISpriteInstance {},
	helmet_BAR_ugrade: class extends self.ISpriteInstance {},
	win_reward_panel: class extends self.ISpriteInstance {},
	button_rocket_buy3: class extends self.ISpriteInstance {},
	highscore_mod_button: class extends self.ISpriteInstance {},
	HIGHSCORE_MOD_TEXT: class extends self.ITextInstance {},
	twp_mode_button: class extends self.ISpriteInstance {},
	TWOPLAYERMODE_TEXT: class extends self.ITextInstance {},
	FADE: class extends self.ISpriteInstance {},
	shieldbuybutton_ugrade: class extends self.ISpriteInstance {},
	powerbuybutton_ugrade: class extends self.ISpriteInstance {},
	arrow_damage_button_ugrade: class extends self.ISpriteInstance {},
	_3_arrowbuybutton_ugrade: class extends self.ISpriteInstance {},
	helmetbuybutton_ugrade: class extends self.ISpriteInstance {},
	_3arrowupgrade_price_ugrade: class extends self.ITextInstance {},
	helmetupgrade_price_ugrade: class extends self.ITextInstance {},
	balance_upgrade_price_text3: class extends self.ITextInstance {},
	reward_fisek: class extends self.ISpriteInstance {},
	fisek_patlayan_iz: class extends self.ISpriteInstance {},
	sandik_part: class extends self.ISpriteInstance {},
	Reward_text: class extends self.ISpriteInstance {},
	start_page_bg: class extends self.ISpriteInstance {},
	logo_alt_zemin: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	click_kenar: class extends self.ISpriteInstance {},
	click_to_continue: class extends self.ITextInstance {},
	panels_ugrade: class extends self.ISpriteInstance {},
	gold_reward2: class extends self.ISpriteInstance {},
	gold_reward3: class extends self.ISpriteInstance {},
	BGBUTON2: class extends self.ISpriteInstance {},
	choose_arrow_tasiyici: class extends self.ISpriteInstance {},
	helmeticon_ugrade: class extends self.ISpriteInstance {},
	armoricon_ugrade: class extends self.ISpriteInstance {},
	povericon_ugrade: class extends self.ISpriteInstance {},
	balanceicon_ugrade: class extends self.ISpriteInstance {},
	healthicon_ugrade: class extends self.ISpriteInstance {},
	lucky_reward: class extends self.ISpriteInstance {},
	luck_frame: class extends self.ISpriteInstance {},
	spin_again_button: class extends self.ISpriteInstance {},
	go_to_menu_button: class extends self.ISpriteInstance {},
	next_battle_button: class extends self.ISpriteInstance {},
	wins_panel_black_bg: class extends self.ISpriteInstance {},
	_3arrowicon_ugrade: class extends self.ISpriteInstance {},
	rise_effect: class extends self.ISpriteInstance {},
	skull: class extends self.ISpriteInstance {},
	drygdf: class extends self.ISpriteInstance {},
	dead_text: class extends self.ITextInstance {},
	BGBUTON3: class extends self.ISpriteInstance {},
	BGBUTON4: class extends self.ISpriteInstance {},
	OK_SEC_TABAN: class extends self.ISpriteInstance {},
	shield_money: class extends self.ISpriteInstance {},
	_3arrow_money: class extends self.ISpriteInstance {},
	helmet_money: class extends self.ISpriteInstance {},
	headshot_reward: class extends self.ISpriteInstance {},
	DEAD_BG: class extends self.ISpriteInstance {},
	replay_button: class extends self.ISpriteInstance {},
	replay_reward_button: class extends self.ISpriteInstance {},
	win_fisek: class extends self.ISpriteInstance {},
	dead_reward: class extends self.ISpriteInstance {},
	day_reward: class extends self.ISpriteInstance {},
	reward_info_text: class extends self.ITextInstance {},
	reward_al_button: class extends self.ISpriteInstance {},
	unlem: class extends self.ISpriteInstance {},
	upgrade_info_text: class extends self.ITextInstance {},
	ON2_pwr: class extends self.ITextInstance {},
	gold_reward_menu: class extends self.ISpriteInstance {},
	or_bilek_baglanti: class extends self.ISpriteInstance {},
	or_ok_baglanti: class extends self.ISpriteInstance {},
	_2pbonus: class extends self.ISpriteInstance {},
	RAPID3: class extends self.ISpriteInstance {},
	skull2: class extends self.ISpriteInstance {},
	BGBUTON6: class extends self.ISpriteInstance {},
	hommm3: class extends self.ISpriteInstance {},
	apple_tasiyici: class extends self.ISpriteInstance {},
	obje_gaz: class extends self.ISpriteInstance {},
	ucan_kaya_blue: class extends self.ISpriteInstance {},
	obje_sandik: class extends self.ISpriteInstance {},
	addcoin: class extends self.ISpriteInstance {},
	ON3: class extends self.ITextInstance {},
	reset: class extends self.ISpriteInstance {},
	or_el_sol: class extends self.ISpriteInstance {},
	or_el_sag: class extends self.ISpriteInstance {},
	Blue_el_sag_clone_3: class extends self.ISpriteInstance {},
	Blue_el_sol_clone_3: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	joybg: class extends self.ISpriteInstance {},
	joy: class extends self.ISpriteInstance {},
	line: class extends self.ISpriteInstance {},
	lineangle: class extends self.ITextInstance {},
	linewidht: class extends self.ITextInstance {},
	iplik: class extends self.ISpriteInstance {},
	iplik2: class extends self.ISpriteInstance {},
	speedd: class extends self.ITextInstance {},
	FireworkParticles: class extends self.IParticlesInstance {},
	kansplash_Particles: class extends self.IParticlesInstance {},
	kan_Particles: class extends self.IParticlesInstance {},
	ok_hit: class extends self.IParticlesInstance {},
	ok_hit_tas_spawner: class extends self.IParticlesInstance {},
	ok_hit2: class extends self.IParticlesInstance {},
	poison_particles_or: class extends self.IParticlesInstance {},
	fire_particles_or: class extends self.IParticlesInstance {},
	duman_particles_or: class extends self.IParticlesInstance {},
	pixel_particles_or: class extends self.IParticlesInstance {},
	HOME: class extends self.ITextInstance {},
	touch_hit: class extends self.IParticlesInstance {},
	touch_line_effect: class extends self.ISpriteInstance {},
	touch_line_effect2: class extends self.ISpriteInstance {},
	fire_impact_particles_or: class extends self.IParticlesInstance {},
	missile_iz_or: class extends self.ISpriteInstance {},
	missile_particles_or: class extends self.IParticlesInstance {},
	govde_duman_particles: class extends self.IParticlesInstance {},
	electiric_light_or: class extends self.ISpriteInstance {},
	bomba_fire_particles: class extends self.IParticlesInstance {},
	bomba_duman_particles: class extends self.IParticlesInstance {},
	headshot_reward2: class extends self.ISpriteInstance {},
	_2p_blue_touch: class extends self.ISpriteInstance {},
	_2p_orange_touch: class extends self.ISpriteInstance {},
	upgradepanel_tasiyici_button: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	ok_yol: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	joy2: class extends self.ISpriteInstance {},
	upgradepanel_bg: class extends self.ISpriteInstance {},
	upgrade_panel_line: class extends self.ISpriteInstance {},
	fire_particles_blue: class extends self.IParticlesInstance {},
	missile_particles_blue: class extends self.IParticlesInstance {},
	missile_iz_or_blue: class extends self.ISpriteInstance {},
	poison_particles_blue: class extends self.IParticlesInstance {},
	pixel_particles_blue: class extends self.IParticlesInstance {},
	duman_particles_blue: class extends self.IParticlesInstance {},
	electiric_light_blue: class extends self.ISpriteInstance {},
	electiric_kivilcim_blue: class extends self.ISpriteInstance {},
	fire_impact_particles_blue: class extends self.IParticlesInstance {},
	bomb_sarapnel: class extends self.ISpriteInstance {},
	touch_tutorial: class extends self.ISpriteInstance {},
	TouchandPull: class extends self.ITextInstance {},
	lock1: class extends self.ISpriteInstance {},
	lock2: class extends self.ISpriteInstance {},
	lock3: class extends self.ISpriteInstance {},
	touch_tutorial_unlock: class extends self.ISpriteInstance {},
	bomb_collison: class extends self.ISpriteInstance {},
	or_scoree2: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	HEALTH_BAR_ugrade2: class extends self.ISpriteInstance {},
	Arm_power: class extends self.ISpriteInstance {},
	arm_power_bonus: class extends self.ISpriteInstance {},
	health_power_bonus: class extends self.ISpriteInstance {},
	arm_zone: class extends self.ISpriteInstance {},
	arm_particle: class extends self.ISpriteInstance {},
	ok_hit3: class extends self.IParticlesInstance {},
	health_power_crash: class extends self.IParticlesInstance {},
	arm_power_crash: class extends self.IParticlesInstance {},
	endscre2: class extends self.ITextInstance {},
	touch_area: class extends self.ISpriteInstance {},
	hand_light: class extends self.ISpriteInstance {},
	bomb_knife: class extends self.ISpriteInstance {},
	gunfruit1_knife: class extends self.ISpriteInstance {},
	bomb_fitil: class extends self.IParticlesInstance {},
	gunfruit1_knife2: class extends self.ISpriteInstance {},
	_3xcombo: class extends self.ISpriteInstance {},
	fruit_bomb: class extends self.IParticlesInstance {},
	_2xcombo: class extends self.ISpriteInstance {},
	or_ok2_knife_hit: class extends self.ISpriteInstance {},
	knifee: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	upgrade_info_text2: class extends self.ITextInstance {},
	text_ugrade2: class extends self.ITextInstance {},
	text_ugrade3: class extends self.ITextInstance {},
	text_ugrade4: class extends self.ITextInstance {},
	text_ugrade5: class extends self.ITextInstance {},
	text_ugrade6: class extends self.ITextInstance {},
	text_ugrade7: class extends self.ITextInstance {},
	ON2_pwr2: class extends self.ITextInstance {},
	ON2_pwr3: class extends self.ITextInstance {},
	choose_arrow_t: class extends self.ITextInstance {},
	health_text_ui: class extends self.ITextInstance {},
	arm_power_text_ui: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	Sound_On_Off_Button: class extends self.ISpriteInstance {},
	Text5: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	home_mods: class extends self.ISpriteInstance {},
	sandik_particle: class extends self.IParticlesInstance {},
	patlama: class extends self.ISpriteInstance {},
	Text7: class extends self.ITextInstance {},
	unlock_arrow: class extends self.ISpriteInstance {},
	unlock_arrow_text: class extends self.ITextInstance {},
	blue_body_part: class extends self.ISpriteInstance {},
	game_tutorial: class extends self.ITextInstance {},
	arrowUnlocked: class extends self.ITextInstance {},
	upgrade_zemin_ugrade: class extends self.ISpriteInstance {},
	thunder_BUTTON_chs: class extends self.ISpriteInstance {},
	saw_BUTTON_chs: class extends self.ISpriteInstance {},
	fuze_BUTTON_chs: class extends self.ISpriteInstance {},
	freeze_BUTTON_chs: class extends self.ISpriteInstance {},
	meteor_BUTTON_chs: class extends self.ISpriteInstance {},
	ayak_sol: class extends self.ISpriteInstance {},
	ayak_sag: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	testere: class extends self.ISpriteInstance {},
	Ice_CPU: class extends self.ISpriteInstance {},
	addcoin2: class extends self.ISpriteInstance {},
	ice: class extends self.ISpriteInstance {},
	freeeze_particle: class extends self.IParticlesInstance {},
	freeze_expl_particle: class extends self.IParticlesInstance {},
	yildirim: class extends self.ISpriteInstance {},
	meteor: class extends self.ISpriteInstance {},
	meteor_particle: class extends self.IParticlesInstance {},
	simsek: class extends self.ISpriteInstance {},
	yildirim_patlama: class extends self.ISpriteInstance {},
	meteor_uc: class extends self.ISpriteInstance {},
	meteordalga: class extends self.ISpriteInstance {},
	meteordalga2: class extends self.ISpriteInstance {},
	ok_fuze: class extends self.ISpriteInstance {},
	fuze: class extends self.ISpriteInstance {},
	fuze_particle: class extends self.IParticlesInstance {},
	panels_ugrade2: class extends self.ISpriteInstance {},
	panels_ugrade3: class extends self.ISpriteInstance {},
	power_tutorial: class extends self.ISpriteInstance {},
	ParticlesAmbience2: class extends self.IParticlesInstance {},
	random_arrow_button: class extends self.ISpriteInstance {},
	panels_ugrade4: class extends self.ISpriteInstance {},
	HEALTH_BAR_ugrade3: class extends self.ISpriteInstance {},
	RAPID4: class extends self.ISpriteInstance {},
	_2p_play_button: class extends self.ISpriteInstance {},
	EndScore: class extends self.ITextInstance {},
	ParticlesAmbience3: class extends self.IParticlesInstance {},
	kukla1: class extends self.ISpriteInstance {},
	kukla2: class extends self.ISpriteInstance {},
	kukla3: class extends self.ISpriteInstance {},
	kuklatoz: class extends self.IParticlesInstance {},
	blue_ayak_sol_clone3: class extends self.ISpriteInstance {},
	blue_ayak_sag_clone3: class extends self.ISpriteInstance {},
	kaya1: class extends self.ISpriteInstance {},
	kaya2: class extends self.ISpriteInstance {},
	kaya3: class extends self.ISpriteInstance {},
	kaya4: class extends self.ISpriteInstance {},
	kaya5: class extends self.ISpriteInstance {},
	kaya6: class extends self.ISpriteInstance {},
	kaya_particle: class extends self.IParticlesInstance {},
	kaya_duman_particle: class extends self.IParticlesInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	el: class extends self.ISpriteInstance {},
	el1: class extends self.ISpriteInstance {},
	el2: class extends self.ISpriteInstance {},
	el3: class extends self.ISpriteInstance {},
	el4: class extends self.ISpriteInstance {},
	okiz: class extends self.ISpriteInstance {},
	okiz2: class extends self.ISpriteInstance {},
	shield_sn_text: class extends self.ITextInstance {},
	_3arrow_sn_text: class extends self.ITextInstance {},
	helmet_sn_text: class extends self.ITextInstance {},
	pixel_particles_boom: class extends self.IParticlesInstance {},
	arm_power_miktar: class extends self.ITextInstance {},
	health_miktar: class extends self.ITextInstance {},
	arrow_damage_miktar: class extends self.ITextInstance {},
	boss_konusma: class extends self.ITextInstance {},
	ucan_kaya_or: class extends self.ISpriteInstance {},
	obje_kaya: class extends self.ISpriteInstance {},
	fire_impact_particles_black: class extends self.IParticlesInstance {},
	yildirim_expl_particle: class extends self.IParticlesInstance {},
	GameDistributionSDK: class extends self.IInstance {},
	Text8: class extends self.ITextInstance {},
	Text9: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Text10: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	panels_ugrade5: class extends self.ISpriteInstance {},
	gold_reward4: class extends self.ISpriteInstance {},
	Text9_replay: class extends self.ITextInstance {},
	or_fizik: class extends self.ISpriteInstance {},
	blue_fizik: class extends self.ISpriteInstance {},
	blue_archer: class extends self.ISpriteInstance {},
	or_archer: class extends self.ISpriteInstance {},
	hersey: class extends self.ISpriteInstance {},
	or_body: class extends self.ISpriteInstance {},
	blue_body: class extends self.ISpriteInstance {},
	dest: class extends self.ISpriteInstance {},
	button: class extends self.ISpriteInstance {},
	blue_archer_clone1: class extends self.ISpriteInstance {},
	blue_body_clone1: class extends self.ISpriteInstance {},
	blue_fizik_clone1: class extends self.ISpriteInstance {},
	blue_fizik_clone2: class extends self.ISpriteInstance {},
	blue_archer_clone2: class extends self.ISpriteInstance {},
	blue_body_clone2: class extends self.ISpriteInstance {},
	blue_fizik_clone3: class extends self.ISpriteInstance {},
	blue_body_clone3: class extends self.ISpriteInstance {},
	blue_archer_clone3: class extends self.ISpriteInstance {},
	blue_fizik_clone4: class extends self.ISpriteInstance {},
	blue_body_clone4: class extends self.ISpriteInstance {},
	blue_archer_clone4: class extends self.ISpriteInstance {},
	yay: class extends self.ISpriteInstance {},
	helmets: class extends self.ISpriteInstance {},
	choose_arrow: class extends self.ISpriteInstance {},
	blues_all: class extends self.ISpriteInstance {},
	wait_dest: class extends self.ISpriteInstance {},
	kemik: class extends self.ISpriteInstance {},
	shields: class extends self.ISpriteInstance {},
	tas_spawner: class extends self.ISpriteInstance {},
	choose_arrow_image: class extends self.ISpriteInstance {},
	choose_arrow_text: class extends self.ITextInstance {},
	finish_tween: class extends self.ISpriteInstance {},
	parts: class extends self.ISpriteInstance {},
	upgrade_panel: class extends self.ISpriteInstance {},
	Text_ugradepanel: class extends self.ITextInstance {},
	blue_archer_all: class extends self.ISpriteInstance {},
	fruit_dest: class extends self.ISpriteInstance {},
	menu_game_dest_text: class extends self.ITextInstance {},
	menu_game_destroy: class extends self.ISpriteInstance {},
	all_texts: class extends self.ITextInstance {},
	game_butn: class extends self.ISpriteInstance {},
	sahnedisiyokol: class extends self.ISpriteInstance {},
	blue_archer_all1: class extends self.ISpriteInstance {},
	blue_archer_all2: class extends self.ISpriteInstance {},
	blue_archer_all3: class extends self.ISpriteInstance {},
	blue_archer_all4: class extends self.ISpriteInstance {},
	kuklafizik: class extends self.ISpriteInstance {},
	blues_target: class extends self.ISpriteInstance {},
	or_archer_target: class extends self.ISpriteInstance {},
	kayafam: class extends self.ISpriteInstance {},
	or_archer_all: class extends self.ISpriteInstance {},
	objeler: class extends self.ISpriteInstance {}
}